package verify

import (
	"crypto/ed25519"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestIntegration_VerifyDemoLic(t *testing.T) {
	licData, err := os.ReadFile("testdata/demo.lic")
	require.NoError(t, err, "testdata/demo.lic must be generated first")

	pubKeyData, err := os.ReadFile("testdata/public.pem")
	require.NoError(t, err, "testdata/public.pem must be generated first")

	pubKey, err := ParsePublicKey(pubKeyData)
	require.NoError(t, err)

	lic, err := VerifyBytes(licData, pubKey)
	require.NoError(t, err)
	require.NotNil(t, lic)
	require.Equal(t, "demo-lic-001", lic.ID)
	require.Equal(t, "travelog", lic.Product)
	require.Equal(t, LicenseTypeStandard, lic.LicenseType)
	require.Equal(t, "Demo Customer", lic.CustomerName)
	require.Equal(t, 5, lic.MaxDevices)

	// Check features
	require.True(t, lic.IsFeatureEnabled("export_pdf"))
	require.True(t, lic.IsFeatureEnabled("export_csv"))
	require.False(t, lic.IsFeatureEnabled("bulk_import"))

	// Check capabilities
	storage := lic.GetCapability("storage_gb")
	require.Equal(t, float64(500), storage)
	tier := lic.GetCapability("tier")
	require.Equal(t, "professional", tier)

	// Check metadata
	require.Equal(t, "cn-beijing", lic.Metadata["region"])

	// Check validity
	require.False(t, lic.IsExpired())
	require.False(t, lic.IsRevoked())
	require.True(t, lic.IsValid())
}

func TestIntegration_VerifyFileWithKeyFile(t *testing.T) {
	lic, err := VerifyFileWithKeyFile("testdata/demo.lic", "testdata/public.pem")
	require.NoError(t, err)
	require.NotNil(t, lic)
	require.Equal(t, "demo-lic-001", lic.ID)
}

func TestIntegration_VerifyFile(t *testing.T) {
	pubKeyData, err := os.ReadFile("testdata/public.pem")
	require.NoError(t, err)
	pubKey, err := ParsePublicKey(pubKeyData)
	require.NoError(t, err)

	lic, err := VerifyFile("testdata/demo.lic", pubKey)
	require.NoError(t, err)
	require.NotNil(t, lic)
}

func TestIntegration_TamperedLic(t *testing.T) {
	pubKeyData, err := os.ReadFile("testdata/public.pem")
	require.NoError(t, err)
	pubKey, err := ParsePublicKey(pubKeyData)
	require.NoError(t, err)

	licData, err := os.ReadFile("testdata/demo.lic")
	require.NoError(t, err)

	// Tamper with the 10th byte of payload to invalidate the signature
	tampered := make([]byte, len(licData))
	copy(tampered, licData)
	content := string(tampered)
	payloadPrefix := "payload: "
	payloadIdx := findLineStart(content, payloadPrefix)
	if payloadIdx >= 0 {
		tampered[payloadIdx] ^= 0xFF
	}

	_, err = VerifyBytes(tampered, pubKey)
	require.Error(t, err)
}

func TestIntegration_WrongPublicKey(t *testing.T) {
	licData, err := os.ReadFile("testdata/demo.lic")
	require.NoError(t, err)

	// Generate a different key
	otherPub, _, err := ed25519.GenerateKey(nil)
	require.NoError(t, err)

	_, err = VerifyBytes(licData, otherPub)
	require.ErrorIs(t, err, ErrInvalidSignature)
}

func findLineStart(content, prefix string) int {
	for i := 0; i <= len(content)-len(prefix); i++ {
		if content[i:i+len(prefix)] == prefix {
			return i + len(prefix)
		}
	}
	return -1
}

func TestIntegration_DecodeAndVerify(t *testing.T) {
	licData, err := os.ReadFile("testdata/demo.lic")
	require.NoError(t, err)

	lf, err := Decode(licData)
	require.NoError(t, err)
	require.Equal(t, "travelog-license-v1", lf.Format)
	require.Equal(t, "Ed25519", lf.Algorithm)
	require.Len(t, lf.SignerKey, 32)
	require.Len(t, lf.Signature, 64)

	// Verify with embedded key
	err = lf.Verify(nil)
	require.NoError(t, err)

	// Parse payload
	lic, err := lf.ParsePayload()
	require.NoError(t, err)
	require.Equal(t, "demo-lic-001", lic.ID)
}

func TestIntegration_CrossCompatibilityWithOriginalFormat(t *testing.T) {
	// This test verifies that our library can parse and verify .lic files
	// generated by the original Travelog License Server
	licData, err := os.ReadFile("testdata/demo.lic")
	require.NoError(t, err)

	pubKeyData, err := os.ReadFile("testdata/public.pem")
	require.NoError(t, err)
	pubKey, err := ParsePublicKey(pubKeyData)
	require.NoError(t, err)

	// Full verification pipeline
	lic, err := VerifyBytes(licData, pubKey)
	require.NoError(t, err)

	// Verify all key fields
	require.Equal(t, "demo-lic-001", lic.ID)
	require.Equal(t, "travelog", lic.Product)
	require.Equal(t, LicenseType("standard"), lic.LicenseType)
	require.Equal(t, "cust-demo-001", lic.CustomerID)
	require.True(t, lic.MaxDevices > 0)

	// Verify the .lic envelope format
	lf, err := Decode(licData)
	require.NoError(t, err)
	require.Equal(t, "travelog-license-v1", lf.Format)
	require.Equal(t, "Ed25519", lf.Algorithm)
	require.Len(t, lf.SignerKey, ed25519.PublicKeySize)
	require.Len(t, lf.Signature, ed25519.SignatureSize)

	// Verify payload can be parsed independently
	parsedLic, err := lf.ParsePayload()
	require.NoError(t, err)
	require.Equal(t, lic.ID, parsedLic.ID)
	require.Equal(t, lic.Product, parsedLic.Product)
}
